/*
 *	Problem 2: Even Fibonacci Numbers
 *	Each new term in the Fibonacci sequence is generated by adding the
 *	previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *	By considering the terms in the Fibonacci sequence whose values do
 *	not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <math.h>

int F( int AN );

int main() {
	unsigned long int the_sum = 0;
	int i = 2;

	while( F(i) <= 4.0e6 ) {
		if( F(i) % 2 == 0 ) { the_sum += F(i); }
		i += 1;
	}

	printf("The sum of the even-valued terms of the Fibonacci sequence up to "
		"4 million is %lu", the_sum);
	return 0;
}

int F( int AN ) {
	if( AN <= 0 ) { return 0; }
	else if( AN == 1 ) { return 1; }
	else {
		return ( pow((1.0 + sqrt(5.0)), AN) - pow((1.0 - sqrt(5.0)), AN) )\
			/ ( pow(2.0, AN) * sqrt(5.0) );
	}
}

