{-----------------------------------------------------------------------------
 - Problem 2: Even Fibonacci Numbers
 -
 - Each new term in the Fibonacci sequence is generated by adding the
 - previous two terms. By starting with 1 and 2, the first 10 terms will be:
 - 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 - 
 - By considering the terms in the Fibonacci sequence whose values do
 - not exceed four million, find the sum of the even-valued terms.
-----------------------------------------------------------------------------}

problem_2 = sumEvenFibs $ numEvenFibsLessThan 4000000
    where
        sumEvenFibs n = (evenFib n + evenFib (n + 1) - 2) `div` 4 
        evenFib n = round $ (2 + sqrt 5) ** (fromIntegral n) / (sqrt 5)
        numEvenFibsLessThan n = floor $ (log (fromIntegral n - 0.5) + 0.5*log 5) / log (2 + sqrt 5)

main = print (problem_2)

