#!/bin/bash

#=============================================================================
#	Problem 2: Even Fibonacci numbers
#
#	Each new term in the Fibonacci sequence is generated by adding the
#	previous two terms. By starting with 1 and 2, the first 10 terms will be:
#			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#	By considering the terms in the Fibonacci sequence whose values do
#	not exceed four million, find the sum of the even-valued terms.
#=============================================================================


the_sum=0
previous=1
current=1

while [ "$current" -le 4000000 ]; do
	# Fibonacci
	temporary=$current
	(( current += previous ))
	previous=$temporary

	# Check for even values, and add to `the_sum`
	if [ $(( $current % 2 )) -eq 0 ]; then
		(( the_sum += current ))
	fi
done

printf "The sum of the even-valued terms of the Fibonacci sequence up to "
printf "4 million is %d\n" $the_sum

